#!/bin/bash

jupyter nbextension enable rubberband/main
jupyter nbextension enable --py widgetsnbextension
jupyter nbextension enable equation-numbering/main
jupyter nbextension enable toc2/main
jupyter nbextension enable python-markdown/main
jupyter nbextension enable hide_input/main
jupyter nbextension enable hide_input_all/main
jupyter nbextension enable latex_envs/latex_envs

